always-show-plot: false
baud-rate: 921600
data:
  latest-generation: 0
  latest-individual: 0
  mutation-rate: 0.001
  population-size: 50
generations:
scale-plots-to-real-units: false
serial-port: /dev/ttyACM1
use-interactive-menu: true
