from enum import Enum


class ToDeviceCommand(Enum):
    COMMAND_NONE_TO_DEVICE = 0
    COMMAND_MOVE_TO_START = 1
    COMMAND_MOVE_TO_TARGET_POSITION = 2
    COMMAND_MOVE_TO_END = 3
    COMMAND_HEALTH_CHECK = 4
    COMMAND_EXECUTE_SEQUENCE = 5
    COMMAND_START_GENETIC_ALGORITHM = 6
    COMMAND_SET_CONFIG = 7
    COMMAND_SET_REGULATION_DATA = 8
    COMMAND_RESTART_DEVICE = 9


class ToHostCommand(Enum):
    COMMAND_NONE_TO_HOST = 0
    COMMAND_PLOT_X = 1
    COMMAND_SET_RESPONSE_DATA = 2
    COMMAND_PRINT_ON_CONSOLE = 3
    COMMAND_GET_CONFIG = 4
